# Generated by Django 4.2.3 on 2023-08-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openness',
            options={'verbose_name': '开放的事件时段', 'verbose_name_plural': '开放的事件时段'},
        ),
        migrations.AlterModelOptions(
            name='reserve',
            options={'verbose_name': '事件', 'verbose_name_plural': '事件'},
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.BooleanField(default=False, verbose_name='是否已经取消'),
        ),
    ]
