# Generated by Django 4.2.3 on 2023-08-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_openness_options_alter_reserve_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='已经取消'),
        ),
    ]
