# Generated by Django 4.2.3 on 2023-08-07 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_customuser_telephone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='submit_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='预约日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='openness',
            name='end_time',
            field=models.DateTimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='openness',
            name='start_time',
            field=models.DateTimeField(verbose_name='开放时间'),
        ),
        migrations.AlterField(
            model_name='record',
            name='submit',
            field=models.DateTimeField(auto_created=True, verbose_name='提交时间'),
        ),
    ]
