# Generated by Django 4.2.3 on 2023-08-07 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_record_submit_date_alter_openness_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='submit_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='预约日期'),
            preserve_default=False,
        ),
    ]
