# Generated by Django 4.2.3 on 2023-08-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_record_reserve_alter_record_submit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='reserve',
            new_name='openness',
        ),
    ]
