# Generated by Django 4.2.3 on 2023-08-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_reserve_record_openness'),
    ]

    operations = [
        migrations.AddField(
            model_name='openness',
            name='max_company',
            field=models.IntegerField(default=1, verbose_name='最大单位数'),
        ),
        migrations.AlterField(
            model_name='openness',
            name='max_person',
            field=models.IntegerField(default=50, verbose_name='最大人数'),
        ),
    ]
